export  const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export  const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export  const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export  const FETCH_ALL_TODO_SUCCESS = 'FETCH_ALL_TODO_SUCCESS';
export  const FETCH_ALL_TODO_REQUEST = 'FETCH_ALL_TODO_REQUEST';
export  const FETCH_ALL_TODO_FAILURE = 'FETCH_ALL_TODO_FAILURE';

export  const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export  const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export  const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';

export  const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export  const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export  const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';

export  const CURRENT_TODO_SUCCESS = 'CURRENT_TODO_SUCCESS';
export  const CURRENT_TODO_REQUEST = 'CURRENT_TODO_REQUEST';
export  const CURRENT_TODO_FAILURE = 'CURRENT_TODO_FAILURE';


