export  const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export  const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export  const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export  const CURRENT_TODO_SUCCESS = 'CURRENT_TODO_SUCCESS';
export  const CURRENT_TODO_REQUEST = 'CURRENT_TODO_REQUEST';
export  const CURRENT_TODO_FAILURE = 'CURRENT_TODO_FAILURE';


