export const contacts = [
  {
    firstName: "Zain",
    lastName: "Ahmad",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Software Engineer",
    favorite: false,
    id: "1",
    name: "Zain 1",
    lastMessage: "hello world 1",
  },
  {
    firstName: "Anas",
    lastName: "Nadeem",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Web developer Engineer",
    favorite: true,
    id: "2",
    name: "John",
    lastMessage: "This is message 2",
  },
  {
    firstName: "Zulqarnain",
    lastName: "Rana",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Full Stack Developer",
    favorite: false,
    id: "3",
    name: "Emma",
    lastMessage: "Hello from Emma",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "4",
    name: "Michael",
    lastMessage: "Greetings from Michael",
  },

  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "5",
    name: "Sarah",
    lastMessage: "Sarah's latest message",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "6",
    name: "Alex",
    lastMessage: "Alex says hi",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "7",
    name: "Sophia",
    lastMessage: "Message from Sophia",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "8",
    name: "Matthew",
    lastMessage: "Matthew's message here",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "9",
    name: "Olivia",
    lastMessage: "Message from Olivia",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "10",
    name: "Daniel",
    lastMessage: "Daniel's latest message",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "11",
    name: "Zain 1",
    lastMessage: "hello world 1",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "12",
    name: "John",
    lastMessage: "This is message 2",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "13",
    name: "Emma",
    lastMessage: "Hello from Emma",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "14",
    name: "Michael",
    lastMessage: "Greetings from Michael",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "15",
    name: "Sarah",
    lastMessage: "Sarah's latest message",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "16",
    name: "Alex",
    lastMessage: "Alex says hi",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "17",
    name: "Sophia",
    lastMessage: "Message from Sophia",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "18",
    name: "Matthew",
    lastMessage: "Matthew's message here",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "19",
    name: "Olivia",
    lastMessage: "Message from Olivia",
  },
  {
    firstName: "Talha",
    lastName: "bhatti",
    lastSeen: Date.now(),
    avatar: "https://placekitten.com/g/200/200",
    twitter: "your_handle",
    notes: "Backend developer",
    favorite: true,
    id: "20",
    name: "Daniel",
    lastMessage: "Daniel's latest message",
  },
];
